### ISSUE TITLE
css inside third party library in node_modules not extracted

### ISSUE THREAD

**Issue by webdevsyd** [prograhammer/vue-pizza#2] opened 2017-05-17 10:23 UTC
Hi David

Been trying different config for webpack but everytime i run the npm run build for production, the css in the .vue files in node_modules folder are not extracted in a separated file but rather injected in the `<head>`

**Comment by prograhammer** [comment] 2017-05-17 13:22
Hi @webdevsyd 

You need to use the **ExtractTextPlugin**(extract-text-webpack-plugin) in your production config. You can see it's used [here](https://github.com/prograhammer/example-vue-project/blob/master/build/webpack.prod.conf.js#L41) in this project. If you do `npm run build` you'll see in the */dist* folder that the Bootstrap CSS (which comes from node_modules, for example) is included in the *app.[some hash here].css* file which then is  included as a `<link>` in your index.html. This is what the **ExtractTextPlugin** is doing.

Take a few hours and read the online SurviveJS book on webpack. It will really help you a lot. Here's a page in the book that talks about separating out your css: https://survivejs.com/webpack/styling/separating-css/

**Comment by webdevsyd** [comment] 2017-05-17 13:40
Yeah. ExtractTextPlugin works on my end if the css is included in the src folder. However if the css styles is included in the .vue template. For example, attached here is the Modal.vue component of vuestrap library that I install. This file is inside the node_modules folder. When I run the npm run build, the css of the Modal.vue component is not inside the app.[some hash here].css but rather injected in the <head> section

<img width="531" alt="screen shot 2017-05-17 at 9 41 31 pm" src="https://cloud.githubusercontent.com/assets/15810023/26156443/f4a84ce0-3b48-11e7-958d-e63c89f33f79.png">

**Comment by prograhammer** [comment] 2017-05-17 17:01
Ok, weird. I see what you are talking about now. I even tried with a fresh untouched template and the styles are still never processed from .vue files in `node_modules`. I posted an issue here you can track along with me: https://github.com/vuejs-templates/webpack/issues/717

**Comment by webdevsyd** [comment] 2017-05-18 02:43
@prograhammer I checked the vendor.js file in dist folder and the css in the .vue template in modules folder are put there that's why it is injected in <head> and not separated in a vendor css file.

**Comment by prograhammer** [comment] 2017-05-19 01:27
Oh stupid me, I was extracting the css in the package I imported, so of course it wasn't there. However, you are right, the css is stuck in the *vendor.[hash].js* file and not being extracted into the parent project's *app.[hash].css*.

**Comment by prograhammer** [comment] 2017-05-19 01:35
^ this looks to be by design and is probably more ideal though, when thinking about caching. Since likely vendor styles would change less and you don't want that included in your app.[hash].css file which will get rehashed more often. Let me see if I can find out how you could go about extracting the styles from the vendor js bundle though before we close this issue.

**Comment by prograhammer** [comment] 2017-05-19 03:01
It seems the ExtractTextPlugin can't catch the chunks created implicitly from the minChunks function of CommonChunkPlugin as you can see [here](https://github.com/prograhammer/example-vue-project/blob/master/build/webpack.prod.conf.js#L69).

**Comment by webdevsyd** [comment] 2017-05-19 05:04
Hi @prograhammer actually I already add the .css in minChunks section but still no luck.

` /\.(js|css)$/.test(module.resource)`

**Comment by prograhammer** [comment] 2017-05-19 05:52
Yeah that's what I'm saying. ExtractTextPlugin can't work with `minChunks`. So you need to add another `entry` and it will pick it up (but again, I would just leave the styles in the vendor.[hash].js and let `minChunks` do it's thing):

        entry: {
            main: './index.js',
            vendor: 'moment'  // <-- ExtractTextPlugin can work with this.
        },

**Comment by prograhammer** [comment] 2017-05-19 10:34
@webdevsyd Try replacing the function in `minChunks` with `/\.(js|vue|css|less)$/`.

**Closed as completed** 2017-05-20 00:39 UTC
